backend/controllers/FakerController.php
<?php

namespace backend\controllers;

use backend\models\FakeAdsForm;
use backend\models\FakeUsersForm;
use common\models\Ads;
use common\models\Category;
use common\models\CustomFields;
use common\models\SubCategory;
use common\models\Transactions;
use common\models\Type;
use common\models\User;
use Faker\Factory;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\helpers\Json;
use yii\data\ActiveDataProvider;
use yii\web\UploadedFile;

/**
 * Faker Controller
 */
class FakerController extends Controller
{

    public function beforeAction($action)
    {
        $control = Yii::$app->params['demo'];
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        };
        if ($control == true and (Yii::$app->request->post() or Yii::$app->request->get())) {
            throw new BadRequestHttpException('Its Demo You Cannot Modify anything');
        } else {
            return parent::beforeAction($action);
        }

    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {

        return $this->render('index');

    }

    public function actionUsers()
    {
        if (\Yii::$app->user->isGuest) {
            return $this->redirect(Url::toRoute('site/login'));
        }
        $searchModel = new User();

        if (isset($_POST['hasEditable'])) {
            $userId = Yii::$app->request->post('editableKey');
            $UserModel = User::findOne($userId);

            // store a default json response as desired by editable
            $out = Json::encode(['output' => '', 'message' => '']);
            $posted = current($_POST['User']);
            $post = ['User' => $posted];
            if ($UserModel->load($post)) {
                // can save model or do something before saving model
                $UserModel->save(false);
            }
            return $out;
        }

        $query_s = User::find()->where(['fake' => '1'])->indexBy('id');
        $dataProvider = new ActiveDataProvider([
            'query' => $query_s,
        ]);


        return $this->render('users', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);

    }

    public function actionUsersCreate()
    {
        $modal = new FakeUsersForm();
        if ($modal->load(Yii::$app->request->post())) {
            $totalAds = $modal['total'];
            $faker = Factory::create("en_US");
            $imgArray = explode(',', $modal->image_directory);

            for ($i = 0; $i < $totalAds; $i++) {
                $fake = new User();
                $fake->first_name = $faker->firstName($modal->gender);
                $fake->last_name = $faker->lastName;
                $fake->username = $faker->userName;
                $fake->email = $faker->email;
                $fake->type = "individual";
                $fake->phone_number = $faker->phoneNumber;
                if ($modal->with_image == true) {
                    $imgRand = $faker->randomElement($imgArray);
                    $fake->image = Self::getImage($imgRand, 'users');
                } else {
                    $fake->image = "default.jpg";
                }
                $fake->phone_number = $faker->phoneNumber;
                $fake->about_you = $faker->realText(['maxNbChars' => 20]);
                $fake->fake = '1';
                $fake->country = $modal['country'];
                $fake->state = $modal['state'];
                $fake->city = $modal['city'];

                $fake->created_at = time();
                $fake->save(false);


            }
            Yii::$app->getSession()->setFlash('success', 'successfully Create ' . $totalAds . ' fakes record');
        }
        return $this->render('users-create', ['modal' => $modal]);

    }

    public function actionAds()
    {

        $modal = new FakeAdsForm();
        $fakesAds = Ads::find()->where(['fake' => '1'])->all();
        if ($modal->load(Yii::$app->request->post())) {
            $totalAds = $modal['total'];
            $faker = Factory::create("en_US");
            $defaultSettings = \common\models\DefaultSetting::getDefaultSetting();

            for ($i = 0; $i < $totalAds; $i++) {

                $fake = new Ads();
                Category::addCounter($modal['category']);
                SubCategory::addCounter($modal['sub_category']);
                $subCatId = SubCategory::findId($modal['sub_category']);

                $fake->user_id = $faker->randomElement(ArrayHelper::map(User::find()->where(['fake' => '1'])->all(), 'id', 'id'));
                $fake->ad_title = $faker->realText(50, 2);
                $fake->ad_description = $faker->realText(1500);
                $fake->category = $modal['category'];
                $fake->sub_category = $modal['sub_category'];

//              =============================  Setting of "TYPE" parameter =====================================
                $randomType = ArrayHelper::map(Type::find()->where(['parent' => $subCatId])->all(), 'name', 'name');
                $type = $faker->randomElement($randomType);
                $fake->type = $type;
                Type::addCounter($type, $modal['sub_category']);
//              ============================  Setting of "TYPE" parameter =====================================

                $fake->ad_type = $faker->randomElement(['public', 'Private']);;
                $fake->currency_symbol = $defaultSettings['currency'];
                $fake->currency_ini = $defaultSettings['currency'];
                $fake->price = $faker->numberBetween($min = 11000, $max = 9000);
                $fake->image = $faker->file($sourceDir = $modal->image_directory, $targetDir = Yii::getAlias('@frontend/web/images/ads/'), false);
                $fake->name = $faker->firstName;
                $fake->mobile = $faker->phoneNumber;
                $fake->email = $faker->email;
                $fake->active = 'yes';
                $fake->premium = $faker->randomElement(['', 'featured', 'urgent']);
                $fake->lat = $faker->latitude;
                $fake->lng = $faker->longitude;
                $fake->country = $defaultSettings['country'];
                $fake->states = $defaultSettings['state'];
                $fake->city = $defaultSettings['city'];
                $fake->address = $faker->address;
                $fake->view = $modal['views'];
                $fake->more = CustomFields::fakerData($modal['sub_category']);
                $fake->created_at = time();
                $fake->updated_at = time();
                $fake->fake = '1';
                $fake->save(false);
            }
            Yii::$app->getSession()->setFlash('success', 'successfully Create ' . $totalAds . ' fakes record');
            return $this->redirect(Url::toRoute('faker/ads'));
        } else {

            $isFake = User::find()->where(['fake' => '1'])->all();;
            if (!$isFake) {
                Yii::$app->getSession()->setFlash('warning', '<b>Warning : </b> You Should create fake users first before create fake ads. Thank you');

                return $this->redirect(Url::toRoute('faker/users'));
            }

            if (isset($_POST['hasEditable'])) {
                $adsId = Yii::$app->request->post('editableKey');
                $ads = Ads::findOne($adsId);

                // store a default json response as desired by editable
                $out = Json::encode(['output' => '', 'message' => '']);
                $posted = current($_POST['Ads']);
                $post = ['Ads' => $posted];
                if ($ads->load($post)) {
                    // can save model or do something before saving model
                    $ads->save(false);
                }
                return $out;;
            }

            $searchModel = new Ads();
            $query_s = Ads::find()->where(['fake' => '1'])->indexBy('id');
            $dataProvider = new ActiveDataProvider([
                'query' => $query_s,
            ]);

            return $this->render('ads', [
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
                'modal' => $modal
            ]);
        }


    }

    public function actionAdsCreate()
    {

        $modal = new FakeAdsForm();
        if ($modal->load(Yii::$app->request->post())) {
            $totalAds = $modal['total'];
            $faker = Factory::create("en_US");
            $defaultSettings = \common\models\DefaultSetting::getDefaultSetting();
            $imgArray = explode(',', $modal->image_directory);

            for ($i = 0; $i < $totalAds; $i++) {

                $fake = new Ads();
                Category::addCounter($modal['category']);
                SubCategory::addCounter($modal['sub_category']);
                $subCatId = SubCategory::findId($modal['sub_category']);

                $fake->user_id = $faker->randomElement(ArrayHelper::map(User::find()->where(['fake' => '1'])->all(), 'id', 'id'));
                $fake->ad_title = $faker->realText(50, 2);
                $fake->ad_description = $faker->realText(1500);
                $fake->category = $modal['category'];
                $fake->sub_category = $modal['sub_category'];

//              =============================  Setting of "TYPE" parameter =====================================
                $randomType = ArrayHelper::map(Type::find()->where(['parent' => $subCatId])->all(), 'name', 'name');
                $type = $faker->randomElement($randomType);
                $fake->type = $type;
                Type::addCounter($type, $modal['sub_category']);
//              ============================  Setting of "TYPE" parameter =====================================

backend/views/faker/ads.php
<?php

/* @var $this yii\web\View */

/* @var $form yii\bootstrap\ActiveForm */

use kartik\grid\GridView;

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\editable\Editable;
use \yii\helpers\Url;

$this->title = 'Create Fake Ads';
$this->params['breadcrumbs'][] = ['label' => 'Faker', 'url' => ['faker/index']];

$this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <div class="d-flex align-items-center">
                <h4 class="card-title">
                    Fake Ads List
                </h4>
                <a class="btn btn-primary btn-round ml-auto" href="<?= Url::toRoute('faker/ads-create') ?>">
                    <i class="la la-plus"></i>
                    Create New Fake Record
                </a>
            </div>
        </div>
        <div class="card-body">


            <?php
            $gridColumns = [
                // the buy_amount column configuration
                ['class' => 'kartik\grid\SerialColumn'],
                ///======== Detail button section =========////

                [
                    'class' => '\kartik\grid\ExpandRowColumn',
                    'header' => 'Detail',
                    // 'headerOptions' => ['style' => 'color:#337ab7'],
                    'expandIcon' => '<span class="flaticon-download-1 text-primary"></span>',

                    'value' => function ($model, $key, $index, $column) {
                        return GridView::ROW_COLLAPSED;
                    },
                    'detailUrl' => Yii::$app->request->getBaseUrl() . '/items/view',
                ],

                ///======== Ads Title section =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'ad_title',
                    'editableOptions' => [
                        'header' => 'Edit Title',
                        'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                    ],
                    'pageSummary' => true
                ],
                ///======== category section =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'category',
                    'pageSummary' => true,
                    'editableOptions' => [
                        'header' => 'Edit Category',
                        'inputType' => Editable::INPUT_TEXT,
                    ],
                ],
                ///======== subcategory section =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'sub_category',
                    'pageSummary' => true,
                    'editableOptions' => [
                        'header' => 'Edit Sub Category',
                        'inputType' => Editable::INPUT_TEXT,
                    ],
                ],
                ///======== ads Type section =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'type',
                    'pageSummary' => true,

                    'editableOptions' => [
                        'header' => 'Edit Ads Type',
                        'inputType' => Editable::INPUT_DROPDOWN_LIST,
                        'data' => ['professional', 'individual'], // any list of values
                    ],
                ],
                ///======== ads Type section =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'ad_type',
                    'pageSummary' => true,

                    'editableOptions' => [
                        'header' => 'Edit Ads type',
                        'inputType' => Editable::INPUT_DROPDOWN_LIST,
                        'data' => ['professional', 'individual'], // any list of values
                    ],
                ],
                ///======== Ads City section =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'city',
                    'pageSummary' => true,

                    'editableOptions' => [
                        'header' => 'Edit Ads City',
                        'inputType' => Editable::INPUT_TEXT,
                    ],
                ],
                ///======== Ads View section =========////
                [
                    'class' => 'kartik\grid\DataColumn',

                    'attribute' => 'view',
                    'pageSummary' => true,

                    'contentOptions' => ['style' => 'color:#337ab7'],

                ],
                ///======== Phone number section =========////
                [
                    'class' => 'kartik\grid\DataColumn',
                    'attribute' => 'user_id',
                    'pageSummary' => true,
                    'header' => 'User',
                    'headerOptions' => ['style' => 'color:#337ab7'],
                    'contentOptions' => ['style' => 'color:#337ab7'],

                    'value' => function ($model) {
                        $userInfo = \common\models\User::findIdentity($model->user_id);//($model->about_you,0,10);
                        return $userInfo['first_name'] . " " . $userInfo['last_name'];
                    },

                ],
                ///======== ads Type section =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'active',
                    'header' => 'Ads Status',
                    'headerOptions' => ['style' => 'color:#337ab7'],
                    'pageSummary' => true,
                    'value' => function ($model) {
                        if ($model->active = 'yes') {
                            return "Active";
                        } elseif ($model->active = 'no') {
                            return "Rejected";
                        } else {
                            return "Pending";
                        }
                    },

                    'editableOptions' => [
                        'header' => 'Edit Ads Status',
                        'inputType' => Editable::INPUT_DROPDOWN_LIST,
                        'data' => ['yes', 'pending', 'no'], // any list of values
                    ],
                ],

                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{leadDelete}',
                    'header' => 'Actions',
                    'headerOptions' => ['style' => 'color:#337ab7'],
                    'buttons' => [

                        'leadDelete' => function ($url, $model, $key) {
                            $url = 'javascript:void()';//Url::to(['controller/lead-delete', 'id' => $model->id]);
                            return Html::a('<span class="flaticon-interface-5"></span>', $url, [
                                'title' => 'delete',
                                'class' => 'record-delete',
                                //'data-confirm' => 'Are you sure you want to delete this item?',//this for pre action confirmation popup box.
                                //'data-method'  => 'post',//this for data method [get/post]
                                'record-delete-msg' => 'Record Deleted',
                                'record-delete-status' => 'active',
                                'record-delete-child' => false,
                                'record-delete-url' => Url::toRoute('delete/user/' . $model->id),
                                'record-data-key' => $key,


                            ]);
                        },
                    ]
                ]

            ];
            ?>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                // 'filterModel' => $searchModel,
                'pjax' => true,
                'pjaxSettings' => [
                    'neverTimeout' => true,
                    'beforeGrid' => 'My fancy content before.',
                    'afterGrid' => 'My fancy content after.',
                ],

                'responsive' => true,
                'floatHeader' => false,
                'containerOptions' => ['style' => 'overflow: auto'], // only set when $responsive = false
                'headerRowOptions' => ['class' => 'kartik-sheet-style'],
                'filterRowOptions' => ['class' => 'kartik-sheet-style'],
//                'toolbar' =>  [
//                    ['content' =>
//                        Html::button('<i class="glyphicon glyphicon-plus"></i>', ['type' => 'button', 'title' => 'Add Book', 'class' => 'btn btn-success', 'onclick' => 'alert("This will launch the book creation form.\n\nDisabled for this demo!");']) . ' '.
//                        Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['grid-demo'], ['data-pjax' => 0, 'class' => 'btn btn-default', 'title' => 'Reset Grid'])
//                    ],
//                    '{export}',
//                    '{toggleData}',
//                ],
                // set export properties
                'export' => [
                    'fontAwesome' => true
                ],

                'columns' => $gridColumns,


            ]) ?>
        </div>
    </div>
</div>

backend/views/faker/index.php
<?php
/**
 * Created by PhpStorm.
 * User: Asus
 * Date: 11-05-2016
 * Time: 11:36
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use Yii\bootstrap\Modal;
use kartik\editable\Editable;
use \yii\helpers\Url;
use kartik\grid\DataColumn;

$this->title = 'Faker - Create Fake data';

?>

<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <div class="d-flex align-items-center">
                <h4 class="card-title">
                    Fake User
                </h4>

            </div>
        </div>
        <div class="card-body" align="center">

            <h1 class="text-success">
                <i class="la la-user"></i>
            </h1>
            <h4 style="color:#999">
                Create Fake User
            </h4>
            <br>

            <a href="<?= Url::toRoute('faker/users') ?>" class="btn btn-block btn-success col-4"> <i
                        class="la la-upload"></i> Create Record </a>


        </div>
        <div class="card-footer ">

        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <div class="d-flex align-items-center">
                <h4 class="card-title">
                    Fake Ads
                </h4>

            </div>
        </div>
        <div class="card-body" align="center">

            <h1 class="text-success">
                <i class="la la-automobile"></i>
            </h1>
            <h4 style="color:#999">
                Create Fake Ads
            </h4>
            <br>

            <a href="<?= Url::toRoute('faker/ads') ?>" class="btn btn-block btn-success col-4"> <i
                        class="la la-upload"></i> Create Record </a>


        </div>
        <div class="card-footer">

        </div>
    </div>
</div>

backend/views/faker/users.php
<?php

/* @var $this yii\web\View */

/* @var $form yii\bootstrap\ActiveForm */

use kartik\grid\GridView;

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\editable\Editable;
use \yii\helpers\Url;

$this->title = 'Fake Users List';
$this->params['breadcrumbs'][] = ['label' => 'Faker', 'url' => ['faker/index']];

$this->params['breadcrumbs'][] = $this->title;
?>

<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <div class="d-flex align-items-center">
                <h4 class="card-title">
                    Fake User List
                </h4>
                <a class="btn btn-primary btn-round ml-auto" href="<?= Url::toRoute('faker/users-create') ?>">
                    <i class="la la-plus"></i>
                    Create New Fake Record
                </a>
            </div>
        </div>
        <div class="card-body">


            <?php
            $gridColumns = [
                // the buy_amount column configuration
                ['class' => 'kartik\grid\SerialColumn'],
                ///======== Detail button section =========////

                [
                    'class' => '\kartik\grid\ExpandRowColumn',
                    'header' => 'Detail',
                    // 'headerOptions' => ['style' => 'color:#337ab7'],
                    'expandIcon' => '<span class="flaticon-download-1 text-primary"></span>',

                    'value' => function ($model, $key, $index, $column) {
                        return GridView::ROW_COLLAPSED;
                    },
                    'detailUrl' => Yii::$app->request->getBaseUrl() . '/site/user-detail',
                ],

                ///======== username section =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'username',
                    'editableOptions' => [
                        'header' => 'Edit Username',
                        'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                    ],
                    'pageSummary' => true
                ],
                ///======== username email =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'email',
                    'pageSummary' => true,
                    'editableOptions' => [
                        'header' => 'Edit Email',
                        'inputType' => Editable::INPUT_TEXT,
                    ],
                ],
                ///======== User Type section =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'type',
                    'pageSummary' => true,

                    'editableOptions' => [
                        'header' => 'Main Category',
                        'inputType' => Editable::INPUT_DROPDOWN_LIST,
                        'data' => ['professional', 'individual'], // any list of values
                    ],
                ],
                ///======== First name section =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'first_name',
                    'pageSummary' => true,

                    'editableOptions' => [
                        'header' => 'Edit First Name',
                        'inputType' => Editable::INPUT_TEXT,
                    ],
                ],
                ///======== Last name section =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'last_name',
                    'pageSummary' => true,

                    'editableOptions' => [
                        'header' => 'Edit Last name',
                        'inputType' => Editable::INPUT_TEXT,
                    ],
                ],
                ///======== Phone number section =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'phone_number',
                    'pageSummary' => true,

                    'editableOptions' => [
                        'header' => 'Edit Phone Number',
                        'inputType' => Editable::INPUT_TEXT,
                    ],
                ],
                ///======== user about section =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'about_you',
                    'pageSummary' => true,
                    'value' => function ($model) {
                        return substr($model->about_you, 0, 10);
                    },

                    'editableOptions' => [
                        'header' => 'EditL User Description',
                        'inputType' => Editable::INPUT_TEXTAREA,
                    ],
                ],
                ///======== user city section =========////
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'city',
                    'pageSummary' => true,

                    'editableOptions' => [
                        'header' => 'Edit User City',
                        'inputType' => Editable::INPUT_TEXT,
                    ],
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{leadDelete}',
                    'header' => 'Actions',
                    'headerOptions' => ['style' => 'color:#337ab7'],
                    'buttons' => [

                        'leadDelete' => function ($url, $model, $key) {
                            $url = 'javascript:void()';//Url::to(['controller/lead-delete', 'id' => $model->id]);
                            return Html::a('<span class="flaticon-interface-5"></span>', $url, [
                                'title' => 'delete',
                                'class' => 'record-delete',
                                //'data-confirm' => 'Are you sure you want to delete this item?',//this for pre action confirmation popup box.
                                //'data-method'  => 'post',//this for data method [get/post]
                                'record-delete-msg' => 'Record Deleted',
                                'record-delete-status' => 'active',
                                'record-delete-child' => false,
                                'record-delete-url' => Url::toRoute('delete/user/' . $model->id),
                                'record-data-key' => $key,


                            ]);
                        },
                    ]
                ]

            ];
            ?>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                // 'filterModel' => $searchModel,
                'pjax' => true,
                'pjaxSettings' => [
                    'neverTimeout' => true,
                    'beforeGrid' => 'My fancy content before.',
                    'afterGrid' => 'My fancy content after.',
                ],

                'responsive' => true,
                'floatHeader' => false,
                'containerOptions' => ['style' => 'overflow: auto'], // only set when $responsive = false
                'headerRowOptions' => ['class' => 'kartik-sheet-style'],
                'filterRowOptions' => ['class' => 'kartik-sheet-style'],
//                'toolbar' =>  [
//                    ['content' =>
//                        Html::button('<i class="glyphicon glyphicon-plus"></i>', ['type' => 'button', 'title' => 'Add Book', 'class' => 'btn btn-success', 'onclick' => 'alert("This will launch the book creation form.\n\nDisabled for this demo!");']) . ' '.
//                        Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['grid-demo'], ['data-pjax' => 0, 'class' => 'btn btn-default', 'title' => 'Reset Grid'])
//                    ],
//                    '{export}',
//                    '{toggleData}',
//                ],
                // set export properties
                'export' => [
                    'fontAwesome' => true
                ],

                'columns' => $gridColumns,


            ]) ?>
        </div>
    </div>
</div>