backend/controllers/PaymentController.php
<?php

namespace backend\controllers;

use common\models\AdsPremium;
use common\models\Payment;
use Yii;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\helpers\Json;
use yii\data\ActiveDataProvider;
use yii\web\NotAcceptableHttpException;

/**
 * StaticsController
 */
class PaymentController extends Controller
{


    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        };
        $model = new AdsPremium();
        $control = Yii::$app->params['demo'];
        if (isset($_POST['hasEditable']) and $control == true) {
            Yii::$app->session->setFlash('error', 'Its Demo You Cannot Modify anything');
            $out = Json::encode(['output' => '', 'message' => 'Its Demo Version You Cannot Change Any Value']);
            return $out;
        };
        if ($control == true and (Yii::$app->request->post() or $model->load(Yii::$app->request->post()))) {
            throw new BadRequestHttpException('Its Demo You Cannot Modify anything');
        } else {
            return parent::beforeAction($action);
        }
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionPaypal()
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        if (isset($_POST['hasEditable'])) {
            $payId = Yii::$app->request->post('editableKey');
            $payment = Payment::findOne($payId);

            // store a default json response as desired by editable
            $out = Json::encode(['output' => '', 'message' => '']);
            $posted = current($_POST['Payment']);
            $post = ['Payment' => $posted];
            if ($payment->load($post)) {
                // can save model or do something before saving model
                if ($payment->save(false)) {
                    $out = Json::encode(['output' => $payment->status, 'message' => '']);
                } else {
                    $out = Json::encode(['output' => 'error', 'message' => 'Failed']);

                }
            }
            return $out;
        }

        $searchModel = new Payment();
        $query_s = Payment::find()->indexBy('id');
        $dataProvider = new ActiveDataProvider([
            'query' => $query_s,
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);

    }

    public function actionIndex()
    {
        if (\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        if (isset($_POST['hasEditable'])) {
            $payId = Yii::$app->request->post('editableKey');
            $payment = Payment::findOne($payId);

            // store a default json response as desired by editable
            $out = Json::encode(['output' => '', 'message' => '']);
            $posted = current($_POST['Payment']);
            $post = ['Payment' => $posted];
            if ($payment->load($post)) {
                // can save model or do something before saving model
                if ($payment->save(false)) {
                    $out = Json::encode(['output' => '', 'message' => '']);
                } else {
                    $out = Json::encode(['output' => 'error', 'message' => 'Failed']);

                }
            }
            return $out;
        }

        $searchModel = new Payment();
        $query_s = Payment::find()->indexBy('id');
        $dataProvider = new ActiveDataProvider([
            'query' => $query_s,
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);


    }

    public function actionAdd()
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new Payment();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                Payment::updateAll(array('status' => 'disable'));
                $model->save(false);///die;
                Yii::$app->getSession()->setFlash('success', 'Update successfully');
                return $this->redirect(Url::toRoute('payment/index'));

            }

        }
        return $this->render('edit', ['model' => $model]);
    }

    public function actionEdit($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = Payment::find()->where('id=' . $id)->one();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                Payment::updateAll(array('status' => 'disable'));
                $model->save();
                Yii::$app->getSession()->setFlash('success', 'Update successfully');

                return $this->redirect(Url::toRoute('payment/index'));

            }
        }
        return $this->render('edit', ['model' => $model]);
    }

    public function actionDelete($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = Payment::find()->where('id=' . $id)->one();
        $model->delete();
        return $this->redirect(Url::toRoute('payment/index'));


    }


    //ads
    public function actionAds()
    {
        $all = AdsPremium::find()->all();
        $new = new AdsPremium();
        if ($new->load(Yii::$app->request->post())) {
            $new->save(false);
            Yii::$app->session->setFlash('success', 'save settings');
        }
        return $this->render('ads_payment_setting', ['all' => $all, 'new' => $new]);
    }

    public function actionAdsEdit($ads)
    {
        $all = AdsPremium::findOne($ads);
        if ($all->load(Yii::$app->request->post())) {
            $all->save(false);
            Yii::$app->session->setFlash('success', 'save settings');
        }
        return $this->render('ads_payment_setting_edit', ['all' => $all, 'new' => $all]);
    }


}

frontend/controllers/PaymentController.php
<?php

namespace frontend\controllers;


use common\models\Ads;
use common\models\AdsPremium;
use common\models\AdsSettings;
use common\models\Crypto;
use common\models\Payment;
use common\models\Transactions;
use common\models\User;
use Yii;
use yii\helpers\Url;
use yii\rest\CreateAction;
use yii\web\Controller;
use Riazxrazor\Payumoney;

/**
 * payment controller
 */
class PaymentController extends Controller
{
    public $layout = 'main';
    public $enableCsrfValidation = false;

    /**
     * @inheritdoc
     */
    public function actionIndex($type, $pid, $price, $service = false)
    {
        $this->layout = "main";

        if ($service) {
            //$type as a service label
            $payment = Payment::find()->where(['name' => 'Paypal'])->one();
            $rerunUrl = Url::toRoute('payment/success', true) . "?type=$type&pid=" . $pid . "&service=true";
            // return $this->redirect(Url::toRoute('payment/success?type='.$type.'&pid='.$pid));

            return $this->render('index', [
                'type' => $type,
                'paypalAddress' => $payment['email'],
                'payment' => $payment,
                'amount' => $price,
                'rerunUrl' => $rerunUrl,
                'item_name' => "Boost Your profile"

            ]);
        } else {
            $payment = Payment::find()->where(['status' => 'enable'])->one();
            // return $this->redirect(Url::toRoute('payment/success?type='.$type.'&pid='.$pid));
            $rerunUrl = Url::toRoute('payment/success', true) . "?type=$type&pid=" . $pid . "&paymentMethod=Paypal&payment_gateway=paypal&price=" . $price;

            return $this->render('index', [
                'type' => $type,
                'paypalAddress' => $payment['email'],
                'payment' => $payment,
                'amount' => $price,
                'rerunUrl' => $rerunUrl,
                'item_name' => $type

            ]);
        }


    }

    public function actionStripe($type, $pid, $price, $service = false)
    {
        $this->layout = "main";

        $payment = Payment::find()->where(['id' => '4'])->one();
        $return = Url::toRoute('payment/success', true) . "?type=$type&pid=" . $pid . "&paymentMethod=credit card&payment_gateway=stripe&price=" . $price;
        // return $this->redirect(Url::toRoute('payment/success?type='.$type.'&pid='.$pid));

        return $this->render('stripe', [
            'type' => $type,
            'payment' => $payment,
            'amount' => $price,
            'return' => $return,
            'item_name' => "Boost Your profile"

        ]);
    }

    public function actionOffline($type, $pid, $price, $service = false)
    {
        $payment = Payment::find()->where(['id' => '7'])->one();
        $configJson = $payment['config'];
        $config = json_decode($configJson, true);
        $adsSetting = AdsSettings::find()->one();
        if ($adsSetting['login_required'] == 0) {
            $userId = null;
        } else {
            $userId = Yii::$app->user->identity->getId();
        }
        $ads = Ads::find()->where(['id' => $pid])->one();
        $ads->premium = $type;;
        $ads->save(false);
        Yii::$app->session->setFlash('info', 'your premium as has been posted');

        //Add($user,$ads,$AdsType,$payment_gateway,$paymentMethod,$status,$amount=false)
        Transactions::Add($userId, $pid, $type, "offline", "offline", 'pending', $price);
        return $this->render('offline', [
            'type' => $type,
            'payment' => $payment,
            'amount' => $price,
            'config' => $config

        ]);
    }

    public function actionPayuMoney($type, $pid, $price, $service = false)
    {
        $ads = Ads::find()->where(['id' => $pid])->one();
        $return = Url::toRoute('payment/success', true) . "?type=$type&pid=" . $pid . "&paymentMethod=Payu Money&payment_gateway=PayuMoney&price=" . $price;

        $payment = Payment::find()->where(['id' => '5'])->one();
        $configJson = $payment['config'];
        $config = json_decode($configJson, true);


        $key = isset($config['KEY']) ? $config['KEY'] : false;
        $salt = isset($config['SALT']) ? $config['SALT'] : false;
        $testMode = ($config['TEST_MODE'] == "true") ? true : false;
        $debug = ($config['DEBUG'] == "true") ? true : false;


        if (!$key) {
            Yii::$app->session->setFlash('danger', 'Stripe key is invalid or empty, please check your Stripe API key');

        }

        $payumoney = new Payumoney\Payumoney([
            'KEY' => $key,
            'SALT' => $salt,
            'TEST_MODE' => $testMode, // optional default to true
            'DEBUG' => $debug // optional default to false
        ]);


        // All of these parameters are required!
        $params = [
            'txnid' => time(),
            'amount' => $price,
            'productinfo' => $type,
            'firstname' => $ads['name'],
            'email' => $ads['email'],
            'phone' => $ads['mobile'],
            'surl' => $return,
            'furl' => $return,
        ];

// Redirects to PayUMoney
        $payumoney->pay($params)->send();

        //$type as a service label
        $payment = Payment::find()->where(['name' => 'PayuMoney'])->one();
        return $this->render('payumoney', [
            'type' => $type,
            'paypalAddress' => $payment['email'],
            'payment' => $payment,
            'amount' => $price,
            'rerunUrl' => $return,
            'item_name' => "Boost Your profile"

        ]);
    }

    public function actionPaytm($type, $pid, $price, $service = false)
    {

        $this->layout = 'main';

        $request = Yii::$app->request->bodyParams;
        $return = Url::toRoute('payment/success', true) . "?type=$type&pid=" . $pid . "&paymentMethod=credit card&payment_gateway=paytm&price=" . $price;
        $payment = Payment::find()->where(['name' => 'paytm'])->one();

        if (isset($request['subscribe'])) {

            $params = [
                'ORDERID' => 'OR7845796587125',
                'CUST_ID' => '123',
                'TXN_AMOUNT' => '30',
                'EMAIL' => 'demo@gmail.com',
                'MOBILE_NO' => '7844759887',
            ];

            \common\components\Paytm::configPaytm($params, 'live');
        }

        return $this->render('paytm', [
            'type' => $type,
            'payment' => $payment,
            'amount' => $price,
            'return' => $return,
            'item_name' => $type

        ]);
    }

    public function actionPaystack($type, $pid, $price, $service = false)
    {

        $this->layout = 'main';

        $request = Yii::$app->request->bodyParams;
        $return = Url::toRoute('payment/success', true) . "?type=$type&pid=" . $pid . "&paymentMethod=paystack&payment_gateway=paystack&price=" . $price;
        $payment = Payment::find()->where(['name' => 'paystack'])->one();

        return $this->render('paystack', [
            'type' => $type,
            'payment' => $payment,
            'amount' => $price,
            'return' => $return,
            'item_name' => $type

        ]);
    }

    public function actionSecure($method, $adsId, $adsType, $amount)
    {


        $session = Yii::$app->session;
        $session->set('adsType', $adsType);
        $session->set('pid', $adsId);
        $session->set('amount', $amount);
        $rerunUrl = Url::to([$method . '/index', 'amount' => $amount]);
        return $this->redirect($rerunUrl);
    }

    public function actionTransaction($tid, $payment_gateway)
    {

        $session = Yii::$app->session;
        $type = $session->get('adsType');
        $pid = $session->get('pid');
        $rerunUrl = Url::toRoute('payment/success', true) . "?type=$type&pid=" . $pid . "&service=true";

        return $this->redirect($rerunUrl);
        //add money in wallet
    }

    public function actionSuccess($type, $pid, $paymentMethod = false, $payment_gateway = false, $price = false)
    {
        $this->layout = "main";


        if ($payment_gateway == "PayuMoney") {
            $payment = Payment::find()->where(['id' => '5'])->one();
            $payumoney = new Payumoney\Payumoney([
                'KEY' => $payment['public_key'],
                'SALT' => $payment['private_key'],
                'TEST_MODE' => true, // optional default to true
                'DEBUG' => true // optional default to false
            ]);

            $result = $payumoney->completePay($_POST);

            $result = $payumoney->completePay($_POST);

// Returns true if the checksum is correct
            $result->checksumIsValid();
            if ($result->checksumIsValid() && $result->isSuccess()) {
                $ads = Ads::find()->where(['id' => $pid])->one();
                $ads->premium = $type;;
                $ads->save(false);
                Yii::$app->session->setFlash('info', 'your premium as has been posted');
                Transactions::Add(Yii::$app->user->identity->getId(), $pid, $type, $paymentMethod, $payment_gateway, 'success', $price);
                $this->redirect(Url::toRoute('user/my-ads'));

            } else {

                Yii::$app->session->setFlash('danger', 'your transaction is fail');
                Yii::$app->session->setFlash('success', 'Ads posted as regular ads');
                return $this->redirect(Url::toRoute('user/my-ads'));
            }


        } elseif ($payment_gateway == "paytm") {
            $toto = new Crypto();
            $paytmParams = $_POST;
            $merchantKey = "7@92&QgCA74g@AzF";
            $paytmChecksum = isset($_POST["CHECKSUMHASH"]) ? $_POST["CHECKSUMHASH"] : "";
            $isValidChecksum = $toto->verifychecksum_e($paytmParams, $merchantKey, $paytmChecksum);
            if ($isValidChecksum == "TRUE") {
                $ads = Ads::find()->where(['id' => $pid])->one();
                $ads->premium = $type;;

backend/views/payment/ads_payment_setting.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;

$this->title = 'Premium Plan';

$uid = Yii::$app->user->id;
$usrInfo = \common\models\User::findOne($uid);
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <div class="d-flex align-items-center">
                <h4 class="card-title">
                    <i class="flaticon-coins"></i> <?= Html::encode($this->title) ?>
                </h4>
            </div>
        </div>
        <div class="card-body">
            <?php
            if (!$all) {
                echo "<p> No premium feature found </p>";
            }
            ?>
            <table class="table table-bordered">
                <tr>
                    <th>Plan Name</th>
                    <th>Plan Price</th>
                    <th>Visible on Home Page</th>
                    <th>Duration</th>
                    <th>Display in</th>
                    <th>Action</th>

                </tr>
                <tbody>

                <?php

                foreach ($all as $list) {
                    ?>

                    <tr>
                        <td>
                            <b class="text-info">  <?= $list->name; ?> </b>
                        </td>
                        <td>

                            <span class="label label-success">$<?= $list->price; ?></span>
                        </td>
                        <td>
                            <span class="label label-info"><?= $list->home_page; ?></span>

                        </td>
                        <td>
                            <span class="label label-info"><?= $list->duration; ?> Month</span>

                        </td>
                        <td>
                            <span class="label label-info"><?= $list->display_in; ?></span>

                        </td>
                        <td class="td-actions text-right">
                            <a href="<?= \yii\helpers\Url::toRoute('payment/ads-edit/' . $list->id) ?>" rel="tooltip"
                               title="Edit Task" class="btn btn-info btn-simple btn-xs">
                                <i class="fa fa-edit"></i>
                            </a>
                        </td>
                    </tr>

                    <?php
                }
                ?>


                </tbody>
            </table>
        </div>
    </div>
</div>

backend/views/payment/ads_payment_setting_edit.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;

$this->title = 'Edit Premium Ads price';

$uid = Yii::$app->user->id;
$usrInfo = \common\models\User::findOne($uid);
$this->params['breadcrumbs'][] = ['label' => 'Premium Plan', 'url' => ['payment/ads']];

$this->params['breadcrumbs'][] = $this->title;

?>
<div class="col-md-6 ml-auto mr-auto">
    <div class="card">
        <div class="card-header">
            <div class="d-flex align-items-center">
                <h4 class="card-title">
                    <i class="flaticon-coins"></i> <?= Html::encode($this->title) ?>
                </h4>
            </div>
        </div>

        <div class="card-body">
            <?php $form = ActiveForm::begin([

                'options' => ['enctype' => 'multipart/form-data']
            ]) ?>

            <?= $form->field($new, 'name')->label("type of ads") ?>
            <?= $form->field($new, 'duration')->dropDownList(array(
                '1' => '1 month',
                '2' => '2 month',
                '3' => '3 month',
                '6' => '6 month',
                '8' => '8 month',
                '10' => '10 month',
                '12' => '12 month',
            ))->label("ad active duration in month") ?>
            <?= $form->field($new, 'display_in')->dropDownList(array(
                'city' => 'inside the city',
                'state' => 'inside the state',
                'country' => 'in the country',
            ))->label("ad active duration in month") ?>
            <?= $form->field($new, 'price')->label("Price of your premium ads") ?>

            <?= $form->field($new, 'home_page')->dropDownList([
                'no' => 'No',
                'yes' => 'Yes '
                ,])->label('ads display at home page?') ?>
            <br>
            <div class="clearfix"></div>

            <div align="center">
                <?= Html::submitButton('Submit', ['class' => 'btn btn-success', 'name' => 'ads-button']) ?>

            </div>

            <div class="clearfix"></div>


            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

backend/views/payment/edit.php
<?php

/* @var $this yii\web\View */

/* @var $form yii\bootstrap\ActiveForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = ' Paypal payment method';
$this->params['breadcrumbs'][] = $this->title;

?>
<style>
    input[type="radio"] {
        display: block;
    }
</style>
<div class="site-login">

    <hr/>
    <div class="row">
        <div class="col-lg-5">
            <div class="panel panel-piluku">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Paypal Setting
                        <span class="panel-options">
                           <a href="#" class="panel-refresh">
                               <i class="icon ti-reload"></i>
                           </a>
                          <a href="#" class="panel-minimize">
                              <i class="icon ti-angle-up"></i>
                          </a>
                          <a href="#" class="panel-close">
                              <i class="icon ti-close"></i>
                          </a>
                      </span>
                    </h3>
                </div>
                <div class="panel-body">
                    <?php $form = ActiveForm::begin(['id' => 'analytic-form']); ?>

                    <?= $form->field($model, 'name')->label('paypal name') ?>

                    <?= $form->field($model, 'email')->label('Paypal email'); ?>

                    <ul class="list-inline checkboxes-radio">
                        <li class="ms-hover">
                            <?= $form->field($model, 'status')->radioList(array('enable' => 'Enable', 'disable' => 'Disable')); ?>

                        </li>
                    </ul>


                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'analytic-button']) ?>
                        <a href="<?= \yii\helpers\Url::toRoute('payment/index') ?>" class="btn btn-info">Back</a>

                    </div>

                    <?php ActiveForm::end(); ?>
                    <!-- /row -->
                </div>
            </div>

        </div>
    </div>
</div>

backend/views/payment/index.php
<?php

/* @var $this yii\web\View */

/* @var $form yii\bootstrap\ActiveForm */

use kartik\grid\GridView;

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\editable\Editable;
use \yii\helpers\Url;

$this->title = 'Payment Gateway Settings';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <div class="d-flex align-items-center">
                <h4 class="card-title">
                    Listed Payment Method
                </h4>

            </div>
        </div>
        <div class="card-body">


            <?php
            $gridColumns = [
                // the buy_amount column configuration
                ['class' => 'kartik\grid\SerialColumn'],

                [
                    'class' => 'kartik\grid\DataColumn',
                    'attribute' => 'name',

                    'pageSummary' => true
                ],


                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'config',
                    'label' => "Config Json",
                    'value' => function ($model) {
                        return substr($model->config, 0, 20);
                    },
                    'editableOptions' => [
                        'header' => 'Edit Config Settings',
                        'inputType' => \kartik\editable\Editable::INPUT_TEXTAREA,
                    ],
                    'pageSummary' => true
                ],
                [
                    //'class'=>'kartik\grid\DataColumn',
                    'attribute' => 'hint',
                    'format' => 'raw',
                    //'pageSummary'=>true,

                    //'contentOptions' => ['style' => 'color:#337ab7'],
                ],
                [
                    'class' => 'kartik\grid\EditableColumn',
                    'attribute' => 'status',
                    'pageSummary' => true,
                    'editableOptions' => [
                        'header' => 'Change Paypal Account Satus',
                        'inputType' => Editable::INPUT_DROPDOWN_LIST,
                        'placement' => \kartik\popover\PopoverX::ALIGN_LEFT,
                        'data' => ['enable' => 'enable', 'disable' => 'disable'], // any list of values
                    ],
                ],


            ];
            ?>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                // 'filterModel' => $searchModel,
                'pjax' => true,
                'pjaxSettings' => [
                    'neverTimeout' => true,
                    'beforeGrid' => 'My fancy content before.',
                    'afterGrid' => 'My fancy content after.',
                ],

                'responsive' => true,
                'floatHeader' => false,
                'containerOptions' => ['style' => 'overflow: auto'], // only set when $responsive = false
                'headerRowOptions' => ['class' => 'kartik-sheet-style'],
                'filterRowOptions' => ['class' => 'kartik-sheet-style'],
//                'toolbar' =>  [
//                    ['content' =>
//                        Html::button('<i class="glyphicon glyphicon-plus"></i>', ['type' => 'button', 'title' => 'Add Book', 'class' => 'btn btn-success', 'onclick' => 'alert("This will launch the book creation form.\n\nDisabled for this demo!");']) . ' '.
//                        Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['grid-demo'], ['data-pjax' => 0, 'class' => 'btn btn-default', 'title' => 'Reset Grid'])
//                    ],
//                    '{export}',
//                    '{toggleData}',
//                ],
                // set export properties
                'export' => [
                    'fontAwesome' => true
                ],

                'columns' => $gridColumns,


            ]) ?>
        </div>
    </div>
</div>

backend/views/payment/paypal.php
<?php
/**
 * Created by PhpStorm.
 * User: Asus
 * Date: 05-03-2016
 * Time: 13:20
 */

$this->title = 'Payment Setting';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-lg-8">
        <h3>Payment settings</h3>
    </div>

    <div class="col-lg-4" align="right">
        <h2>
            <a href="<?= \yii\helpers\Url::toRoute('payment/add') ?>" class="btn btn-sm btn-info">Add new</a>

        </h2>

    </div>


    <div class="col-lg-12">
        <hr>
        <div class="list-group">
            <?php
            foreach ($payment as $code) {
                ?>
                <div class="list-group-item">
                    <a href="#" title="status" data-toggle="popover" data-placement="right"
                       data-content="<?= $code['status']; ?>">

                        <?php
                        if ($code['status'] == "enable") {
                            echo "<i title='selected' class='fa fa-check-circle'></i> &nbsp;" . $code['name'];
                        } else {
                            echo "<span>&nbsp;&nbsp;&nbsp;</span>;" . $code['name'];

                        }
                        ?>
                    </a>


                    <div style="float: right;display: block">
                        <a title="Edit"
                           href="<?= \yii\helpers\Url::to('index.php?r=payment/edit&id=' . $code['id'], false) ?>">
                            <span class="fa fa-pencil"></span>
                        </a>
                        <a title="Delete"
                           href="<?= \yii\helpers\Url::toRoute('index.php?r=payment/delete&id=' . $code['id'], false) ?>">
                            <span class="fa fa-trash"></span>
                        </a>

                    </div>
                </div>
                <?php
            }
            ?>

        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('[data-toggle="popover"]').popover();
    });
</script>